# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b92b4536710545dd21120bdc28b131974bfbf3973eff0f77a29da00c1a60970f269f7163c0062bbfcdf1159cf0f6e52920be9e8aa0b61ebd3ac3f3d53e322314

test:
  secret_key_base: 6f67f2ba4de08d78a68751b0c49c43e93afa93b1d61a275461a14993a1366e15699682cb7f670b6265e28557707dc7ea5d8a388f9194e405691564297a4b5dfc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
